-- Migration data for monitoring_checks table
-- Generated from old database on 2025-07-17

-- Insert monitoring_checks data
INSERT INTO public.monitoring_checks (
    id,
    organization_id,
    name,
    description,
    check_type,
    target_url,
    target_port,
    target_timeout,
    configuration,
    check_interval,
    retry_count,
    retry_interval,
    monitoring_locations,
    status,
    maintenance_windows,
    alert_after_failures,
    alert_on_recovery,
    escalation_policy_id,
    status_page_component_id,
    auto_update_status,
    tags,
    created_by,
    created_at,
    updated_at
) VALUES 
(
    '301fa220-aced-409c-810c-50e18395cec5',
    '80fe7a23-0a4d-461b-bb4a-f0a5fd251781',
    'IHQ - Home',
    '',
    'http',
    'https://inventivehq.com',
    NULL,
    30,
    '{"http_method": "GET", "http_headers": {}, "follow_redirects": true, "ssl_check_enabled": false, "expected_status_codes": [200]}'::jsonb,
    300,
    3,
    60,
    NULL,
    'active',
    '[]'::jsonb,
    2,
    true,
    NULL,
    NULL,
    true,
    NULL,
    '3b3e5e75-a6ca-4680-83b0-35455901f1d1',
    '2025-07-07T03:44:29.045Z',
    '2025-07-07T03:44:29.045Z'
),
(
    '92eaa216-cbd8-4c2c-889b-91928b29163c',
    '80fe7a23-0a4d-461b-bb4a-f0a5fd251781',
    'Test broken link',
    '',
    'http',
    'http://sdfjsdlk.com/',
    NULL,
    30,
    '{"http_method": "GET", "http_headers": {}, "follow_redirects": true, "ssl_check_enabled": true, "expected_status_codes": [200]}'::jsonb,
    300,
    3,
    60,
    NULL,
    'active',
    '[]'::jsonb,
    2,
    true,
    NULL,
    NULL,
    true,
    NULL,
    '3b3e5e75-a6ca-4680-83b0-35455901f1d1',
    '2025-07-07T03:56:35.433Z',
    '2025-07-07T03:56:35.433Z'
)
ON CONFLICT (id) DO UPDATE SET
    organization_id = EXCLUDED.organization_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    check_type = EXCLUDED.check_type,
    target_url = EXCLUDED.target_url,
    target_port = EXCLUDED.target_port,
    target_timeout = EXCLUDED.target_timeout,
    configuration = EXCLUDED.configuration,
    check_interval = EXCLUDED.check_interval,
    retry_count = EXCLUDED.retry_count,
    retry_interval = EXCLUDED.retry_interval,
    monitoring_locations = EXCLUDED.monitoring_locations,
    status = EXCLUDED.status,
    maintenance_windows = EXCLUDED.maintenance_windows,
    alert_after_failures = EXCLUDED.alert_after_failures,
    alert_on_recovery = EXCLUDED.alert_on_recovery,
    escalation_policy_id = EXCLUDED.escalation_policy_id,
    status_page_component_id = EXCLUDED.status_page_component_id,
    auto_update_status = EXCLUDED.auto_update_status,
    tags = EXCLUDED.tags,
    created_by = EXCLUDED.created_by,
    updated_at = EXCLUDED.updated_at; 