-- Migration data for users table
-- Generated from old database on 2025-07-17

-- Insert users data
INSERT INTO public.users (
    id,
    email,
    name,
    avatar_url,
    google_oauth_id,
    google_id,
    password,
    timezone,
    language,
    email_notifications_enabled,
    push_notifications_enabled,
    is_active,
    last_login_at,
    created_at,
    updated_at,
    deleted_at,
    incident_role,
    is_on_call,
    current_on_call_schedule_id,
    phone_number,
    slack_user_id,
    teams_user_id,
    notification_preferences
) VALUES 
(
    'a3169d26-2691-445b-8298-a58efe976c09',
    'sean@econroy.com',
    'sean@econroy.com',
    NULL,
    NULL,
    NULL,
    NULL,
    'UTC',
    'en',
    true,
    true,
    true,
    NULL,
    '2025-07-07T02:13:18.541Z',
    '2025-07-07T02:13:18.541Z',
    NULL,
    'viewer',
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb
),
(
    '3b3e5e75-a6ca-4680-83b0-35455901f1d1',
    'sean@inventivehq.com',
    'Sean Conroy',
    NULL,
    NULL,
    NULL,
    '$2b$10$im8ZAx7EUsVJAQ2VSWdk.e1ZmxSWzrN3OIA8aMZGl9gOv.dj9KBGO',
    'America/Los_Angeles',
    'en',
    true,
    true,
    true,
    NULL,
    '2025-07-03T17:36:43.684Z',
    '2025-07-07T02:23:36.602Z',
    NULL,
    'viewer',
    false,
    NULL,
    '+17073269485',
    NULL,
    NULL,
    '{"sms_critical": true, "email_incidents": true, "sms_escalations": true, "email_escalations": true}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    google_oauth_id = EXCLUDED.google_oauth_id,
    google_id = EXCLUDED.google_id,
    password = EXCLUDED.password,
    timezone = EXCLUDED.timezone,
    language = EXCLUDED.language,
    email_notifications_enabled = EXCLUDED.email_notifications_enabled,
    push_notifications_enabled = EXCLUDED.push_notifications_enabled,
    is_active = EXCLUDED.is_active,
    last_login_at = EXCLUDED.last_login_at,
    updated_at = EXCLUDED.updated_at,
    deleted_at = EXCLUDED.deleted_at,
    incident_role = EXCLUDED.incident_role,
    is_on_call = EXCLUDED.is_on_call,
    current_on_call_schedule_id = EXCLUDED.current_on_call_schedule_id,
    phone_number = EXCLUDED.phone_number,
    slack_user_id = EXCLUDED.slack_user_id,
    teams_user_id = EXCLUDED.teams_user_id,
    notification_preferences = EXCLUDED.notification_preferences; 