-- Migration data for organizations table
-- Generated from old database on 2025-07-17

-- Insert organizations data
INSERT INTO public.organizations (
    id,
    name,
    slug,
    domain,
    subdomain,
    logo_url,
    primary_color,
    secondary_color,
    custom_css,
    subscription_plan,
    stripe_customer_id,
    stripe_subscription_id,
    subscription_status,
    current_period_start,
    current_period_end,
    max_team_members,
    max_projects,
    created_at,
    updated_at,
    deleted_at
) VALUES 
(
    '5e4107b7-9a16-4555-9bf2-c10ce9684e98',
    'TestOrg1',
    'testorg1',
    'testorg1.alert24.com',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'free',
    NULL,
    NULL,
    'active',
    NULL,
    NULL,
    3,
    5,
    '2025-07-03T18:58:26.853Z',
    '2025-07-03T18:58:26.853Z',
    NULL
),
(
    '8b2e7859-1dc9-4de3-99d4-ee777f99adc5',
    'Your Organization',
    'your-org',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'free',
    NULL,
    NULL,
    'active',
    NULL,
    NULL,
    3,
    5,
    '2025-07-03T19:41:05.332Z',
    '2025-07-03T19:41:05.332Z',
    NULL
),
(
    'e4ee98dd-afc5-45a1-8afa-ff1b93b9105c',
    'Org1',
    'org1',
    'org1.alert24.com',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'free',
    NULL,
    NULL,
    'active',
    NULL,
    NULL,
    3,
    5,
    '2025-07-03T19:44:03.116Z',
    '2025-07-03T19:44:03.116Z',
    NULL
),
(
    '80fe7a23-0a4d-461b-bb4a-f0a5fd251781',
    'My Amazing Company',
    'my-amazing-company',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'free',
    NULL,
    NULL,
    'active',
    NULL,
    NULL,
    3,
    5,
    '2025-07-03T20:53:00.934Z',
    '2025-07-03T20:53:00.934Z',
    NULL
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    domain = EXCLUDED.domain,
    subdomain = EXCLUDED.subdomain,
    logo_url = EXCLUDED.logo_url,
    primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    custom_css = EXCLUDED.custom_css,
    subscription_plan = EXCLUDED.subscription_plan,
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    subscription_status = EXCLUDED.subscription_status,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    max_team_members = EXCLUDED.max_team_members,
    max_projects = EXCLUDED.max_projects,
    updated_at = EXCLUDED.updated_at,
    deleted_at = EXCLUDED.deleted_at; 