name = "alert24-app"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "alert24-app"

[[env.production.d1_databases]]
binding = "DB"
database_name = "alert24-db"
database_id = "your-database-id-here"

[env.development]
name = "alert24-app-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "alert24-db-dev"
preview_database_id = "your-preview-database-id-here"

# Local development
[[d1_databases]]
binding = "DB"
database_name = "alert24-db-local"
database_id = "local"

[vars]
ENVIRONMENT = "development" 